### ISSUE TITLE
Electron App

### ISSUE THREAD

**Issue by bkonia** [dundalek/markmap#20]
It would be awesome if you could turn this into an Electron app and provide a MacOS share extension, so users could visualize Markdown created in any app.

**Comment by dundalek** [comment]
Are you aware of the [Atom plugin](https://atom.io/packages/markdown-mindmap)? You can open and visualize any file in it.

That covers my needs, so I don't personally need an Electron app. Therefore I won't probably work on it, but will keep the issue open so that anyone from the community can decide to pick it up.

**Comment by bkonia** [comment]
Yes, I was aware of it, but I don't use Atom and I think it would be cool to be able to visualize Markdown from any editor. Anyway, thanks for leaving this open. Hopefully someone will do it, as it would be a great app.

**Comment by danloh** [comment]
Here is a app built with Tauri based on this amazing pkg.  
Available for macOS, Linux and Windows:  https://github.com/danloh/mdSilo-app

**Comment by dundalek** [comment]
Thanks @danloh, that's a nice project. I added a link to the readme. I think that concludes the issue :)
